# Introduction to NumPy

In [42]:
import numpy as np

In [2]:
array = np.array([1,2,3,4,5])
array #Esto es un objeto de numpy, NO es un arreglo

array([1, 2, 3, 4, 5])

In [3]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix #Matriz 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.arange(10) #Shift + TAB obtenemos la ayuda y podemos visualizar qué parámetro es obligatorio

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [6]:
np.arange(5, 20, 3)

array([ 5,  8, 11, 14, 17])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((5, 8)) # 5 x 8

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
np.ones((5, 8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.linspace(0, 5, 11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [14]:
np.random.rand()

0.878053080954637

In [15]:
np.random.rand(5)

array([0.91021901, 0.99886285, 0.50140885, 0.85231482, 0.0189979 ])

In [17]:
np.random.rand(2, 4) #Todos los números tienen la misma probabilidad de salir

array([[0.36233346, 0.99521926, 0.32928406, 0.08462243],
       [0.26751601, 0.35985178, 0.03936409, 0.61714628]])

In [20]:
np.random.randn(2, 4) #Solo cambia la distribución a la Campana de Bell <Distribución Gaussiana>

array([[-0.86126096, -0.18332832,  0.57370834,  2.23594348],
       [-0.29667288,  1.15191436, -0.19997654,  0.25738346]])

In [21]:
np.random.seed(100)

In [22]:
np.random.rand((5))

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [23]:
np.random.randint(1, 100, (3, 3))

array([[99, 54, 67],
       [99, 15, 35],
       [25, 16, 61]])

In [25]:
array = np.arange(0, 24)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [26]:
array.reshape((6, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
array.reshape((4, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [29]:
array.reshape((12, 2)) #Recordar que el array original nunca cambia hasta que se le asigne el cambio

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [46]:
array = np.random.randint(1, 100, 10)
array

array([14, 84,  5, 92, 60, 68,  8, 50, 48, 66])

In [47]:
array.sum()

495

In [48]:
array.min()

5

In [49]:
array.max()

92

In [50]:
array.mean()

49.5

In [51]:
np.average(array)

49.5

In [52]:
np.cos(array)

array([ 0.13673722, -0.6800235 ,  0.28366219, -0.62644445, -0.95241298,
        0.44014302, -0.14550003,  0.96496603, -0.64014434, -0.99964746])

In [53]:
np.max(array)

92

In [54]:
array.argmax() #Índice del máximo

3

In [55]:
array.argmin() #Índice del mínimo

2

In [56]:
array.shape

(10,)

In [57]:
np.zeros((2, 3)).shape

(2, 3)

In [58]:
array.dtype

dtype('int32')

# NumPy array indexing and selection 

In [59]:
array = np.random.randint(1, 100, 10)
array

array([62, 15, 56, 72, 81,  3, 95, 20, 99, 64])

In [60]:
array[8]

99

In [61]:
array[8] = 152
array

array([ 62,  15,  56,  72,  81,   3,  95,  20, 152,  64])

In [62]:
array[3:7]

array([72, 81,  3, 95])

In [63]:
array[3:7] = [50]
array

array([ 62,  15,  56,  50,  50,  50,  50,  20, 152,  64])

In [69]:
aux_array = array[3:7]
aux_array[1:3] = 0
print(aux_array)
print(array)

[99  0  0 99]
[ 62  15  56  99   0   0  99  20 152  64]


In [71]:
matrix = np.random.randint(1, 100, (10, 10))
matrix

array([[90, 73, 31, 13, 19, 94, 93, 45, 58,  1],
       [74, 55, 93, 67, 17,  6, 52, 91, 35, 68],
       [95, 79, 55, 78, 85,  2, 15, 34, 21, 41],
       [25, 94, 59, 29, 83, 83,  8, 95,  3, 64],
       [ 3, 88, 18, 91, 94, 97, 75, 54, 31, 68],
       [29, 38, 83, 18, 11, 14, 82, 26, 67, 16],
       [12, 39, 23, 56, 58, 88, 52, 49, 54, 18],
       [66, 43, 94, 45, 17, 52, 55, 56, 84, 43],
       [62, 38, 81,  3, 63, 82, 17, 71, 54, 99],
       [97, 48, 49, 10, 50, 54, 35,  4, 12, 50]])

In [74]:
matrix[2:5, 3:6] = -1

In [75]:
matrix

array([[90, 73, 31, 13, 19, 94, 93, 45, 58,  1],
       [74, 55, 93, 67, 17,  6, 52, 91, 35, 68],
       [95, 79, 55, -1, -1, -1, 15, 34, 21, 41],
       [25, 94, 59, -1, -1, -1,  8, 95,  3, 64],
       [ 3, 88, 18, -1, -1, -1, 75, 54, 31, 68],
       [29, 38, 83, 18, 11, 14, 82, 26, 67, 16],
       [12, 39, 23, 56, 58, 88, 52, 49, 54, 18],
       [66, 43, 94, 45, 17, 52, 55, 56, 84, 43],
       [62, 38, 81,  3, 63, 82, 17, 71, 54, 99],
       [97, 48, 49, 10, 50, 54, 35,  4, 12, 50]])

In [81]:
matrix[1:9, 1:9] = -1
matrix

array([[90, 73, 31, 13, 19, 94, 93, 45, 58,  1],
       [74, -1, -1, -1, -1, -1, -1, -1, -1, 68],
       [95, -1, -1, -1, -1, -1, -1, -1, -1, 41],
       [25, -1, -1, -1, -1, -1, -1, -1, -1, 64],
       [ 3, -1, -1, -1, -1, -1, -1, -1, -1, 68],
       [29, -1, -1, -1, -1, -1, -1, -1, -1, 16],
       [12, -1, -1, -1, -1, -1, -1, -1, -1, 18],
       [66, -1, -1, -1, -1, -1, -1, -1, -1, 43],
       [62, -1, -1, -1, -1, -1, -1, -1, -1, 99],
       [97, 48, 49, 10, 50, 54, 35,  4, 12, 50]])

In [82]:
matrix>50

array([[ True,  True, False, False, False,  True,  True, False,  True,
        False],
       [ True, False, False, False, False, False, False, False, False,
         True],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
         True],
       [False, False, False, False, False, False, False, False, False,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
         True],
       [ True, False, False, False, False,  True, False, False, False,
        False]])

In [83]:
matrix[(matrix>=50) & (matrix<=80)]

array([73, 58, 74, 68, 64, 68, 66, 62, 50, 54, 50])

In [84]:
matrix/100

array([[ 0.9 ,  0.73,  0.31,  0.13,  0.19,  0.94,  0.93,  0.45,  0.58,
         0.01],
       [ 0.74, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01,
         0.68],
       [ 0.95, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01,
         0.41],
       [ 0.25, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01,
         0.64],
       [ 0.03, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01,
         0.68],
       [ 0.29, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01,
         0.16],
       [ 0.12, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01,
         0.18],
       [ 0.66, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01,
         0.43],
       [ 0.62, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01,
         0.99],
       [ 0.97,  0.48,  0.49,  0.1 ,  0.5 ,  0.54,  0.35,  0.04,  0.12,
         0.5 ]])